### ISSUE TITLE
NPE with version 3.2.0

### ISSUE THREAD

**Issue by varjasz** [vanioinformatika/easydao#18]
The following error occured with version 3.2.0 (run without error with version 3.0.2):

[ERROR] Failed to execute goal hu.vanio.maven.plugins:easydao-maven-plugin:3.2.0:generate (default) on project iszl-db: Execution default of goal hu.vanio.maven.plugins:easydao-maven-plugin:3.2.0:generate failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal hu.vanio.maven.plugins:easydao-maven-plugin:3.2.0:generate (default) on project iszl-db: Execution default of goal hu.vanio.maven.plugins:easydao-maven-plugin:3.2.0:generate failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal hu.vanio.maven.plugins:easydao-maven-plugin:3.2.0:generate failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 20 more
Caused by: java.lang.NullPointerException
	at hu.vanio.easydao.modelbuilder.ModelBuilder.getCustomType(ModelBuilder.java:425)
	at hu.vanio.easydao.modelbuilder.ModelBuilder.getFieldList(ModelBuilder.java:387)
	at hu.vanio.easydao.modelbuilder.ModelBuilder.build(ModelBuilder.java:144)
	at hu.vanio.easydao.Engine.execute(Engine.java:119)
	at hu.vanio.maven.plugins.easydao.Generator.execute(Generator.java:311)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 21 more

**Comment by patoi** [comment]
At https://github.com/vanioinformatika/easydao/blob/a13aa0f313d27aa176f9f9490342c60eed59d78d/easydao-maven-plugin/src/main/java/hu/vanio/easydao/modelbuilder/ModelBuilder.java#L425 throws an exception, because `customTypeMap` is null.

At https://github.com/vanioinformatika/easydao/blob/a13aa0f313d27aa176f9f9490342c60eed59d78d/easydao-maven-plugin/src/main/java/hu/vanio/easydao/modelbuilder/ModelBuilder.java#L118 `customTypeMap` is initialised, but if config doesn't contains `replacementTypeMap` element, then `customTypeMap` is null.

```java
if (replacementTypeMap != null && !replacementTypeMap.isEmpty()) {
            this.customTypeMap = new HashMap<>();
```
